# Generated by Django 4.0.5 on 2022-06-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0003_alter_departamento_anulate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['-name'], 'verbose_name': 'Mi departamento', 'verbose_name_plural': 'Áreas de la empresa'},
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='short_name',
            new_name='shor_name',
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('name', 'shor_name')},
        ),
    ]
